"""users table

Revision ID: 1bf2dc07e78c
Revises: 4f116f023078
Create Date: 2019-12-12 10:32:45.471286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bf2dc07e78c'
down_revision = '4f116f023078'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('location', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_employees_location'), 'employees', ['location'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employees_location'), table_name='employees')
    op.drop_column('employees', 'location')
    # ### end Alembic commands ###
