"""users table

Revision ID: 4f116f023078
Revises: b1e6e2b0412d
Create Date: 2019-11-26 12:45:30.214842

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4f116f023078'
down_revision = 'b1e6e2b0412d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('about_me2', mysql.LONGTEXT(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'about_me2')
    # ### end Alembic commands ###
